version: "3"

services:
  appnode:
    build:
      context: ./node
    container_name: appnode
    entrypoint: dockerize -wait tcp://mysqldb:3306 -timeout 50s node index.js
    networks:
      - node-network
    tty: true
    ports:
      - "4000:4000"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.6
    command: --innodb-use-native-aio=0
    container_name: mysqldb
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=nodedb
      - MYSQL_PASSWORD=nodedb
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nodenginx
    restart: unless-stopped
    depends_on:
      - appnode
    volumes:
      - ./nginx/web-root:/var/www/html
    networks:
      - node-network
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge
